#Github workflow for triggering PR
#
#SPDX-FileCopyrightText: 2023 Birger Schacht
#SPDX-License-Identifier: MIT

name: "Trigger a PR in the ontologies repo with the changes to the datamodel"

on:
  push:
    branches: main
    paths:
      - 'model.xml'
      - 'methods/*.py'
  workflow_dispatch:

jobs:
  build:
    name: "Trigger PR"
    runs-on: ubuntu-22.04

    steps:
     - name: Use curl to trigger the workflow run
       run: |
         curl -H "Accept: application/vnd.github.everest-preview+json" \
           -H "Authorization: token ${PR_TOKEN}" \
           --request POST \
           --data '{"event_type": "createpr"}' \
           https://api.github.com/repos/acdh-oeaw/apis-ontologies/dispatches
       env:
         PR_TOKEN: ${{ secrets.PR_TOKEN }}
